//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BartUI.SimpleProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleProxy.IBartService")]
    public interface IBartService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBartService/GetIssue", ReplyAction="http://tempuri.org/IBartService/GetIssueResponse")]
        ServiceLibrary.IssueResponse GetIssue(string id, ServiceLibrary.IssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBartService/GetIssue", ReplyAction="http://tempuri.org/IBartService/GetIssueResponse")]
        System.Threading.Tasks.Task<ServiceLibrary.IssueResponse> GetIssueAsync(string id, ServiceLibrary.IssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBartService/GetBigObject", ReplyAction="http://tempuri.org/IBartService/GetBigObjectResponse")]
        ServiceLibrary.BigObject GetBigObject(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBartService/GetBigObject", ReplyAction="http://tempuri.org/IBartService/GetBigObjectResponse")]
        System.Threading.Tasks.Task<ServiceLibrary.BigObject> GetBigObjectAsync(int size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBartServiceChannel : BartUI.SimpleProxy.IBartService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BartServiceClient : System.ServiceModel.ClientBase<BartUI.SimpleProxy.IBartService>, BartUI.SimpleProxy.IBartService {
        
        public BartServiceClient() {
        }
        
        public BartServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BartServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BartServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BartServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceLibrary.IssueResponse GetIssue(string id, ServiceLibrary.IssueRequest request) {
            return base.Channel.GetIssue(id, request);
        }
        
        public System.Threading.Tasks.Task<ServiceLibrary.IssueResponse> GetIssueAsync(string id, ServiceLibrary.IssueRequest request) {
            return base.Channel.GetIssueAsync(id, request);
        }
        
        public ServiceLibrary.BigObject GetBigObject(int size) {
            return base.Channel.GetBigObject(size);
        }
        
        public System.Threading.Tasks.Task<ServiceLibrary.BigObject> GetBigObjectAsync(int size) {
            return base.Channel.GetBigObjectAsync(size);
        }
    }
}
